//
//  SendMoneyInterfaces.swift
//  Penguin Pay
//
//  Created by John Edwin Guerrero Ayala on 16/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol SendMoneyWireframeInterface: WireframeInterface {
    func presentSendPaymentAlert()
}

protocol SendMoneyViewInterface: ViewInterface {
    func updateRecipientForm(withAmount amount: String)
    func updateRecipientForm(withCountry country: Country)
    func updateSendButtonState(_ enabled: Bool)
    func resetView()
}

protocol SendMoneyPresenterInterface: PresenterInterface {
    var countries: [Country] { get set }
    var recipientFirstName: String { get set }
    var recipientLastName: String { get set }
    var recipientPhoneNumber: String { get set }
    var recipientAmount: String { get set }
    var selectedCountry: Country? { get set }
    var isFormComplete: Bool { get }
    func viewDidLoad()
    func calculateExchange(to currencyCode: String, amount: String) -> String
    func updateRecipientExchange(to currencyCode: String, amount: String)
    func updateSendingButtonState()
    func sendPayment()
}

protocol SendMoneyFormatterInterface: FormatterInterface {
    func binaryAmount(fromUInt uintNumber: UInt32) -> String
    func binaryAmount(fromFloat floatNumber: Float) -> String
    func intAmount(fromBinary binaryNumber: String) -> UInt32
    func floatAmount(fromBinary binaryNumber: String) -> Float
}

protocol SendMoneyInteractorInterface: InteractorInterface {
    func updateExchangeRates(completion: @escaping (_ error: Error?) -> Void)
    func exchangeRate(for currencyCode: String) -> Float
}
