//
//  SendMoneyViewController.swift
//  Penguin Pay
//
//  Created by John Edwin Guerrero Ayala on 16/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SendMoneyViewController: UIViewController {
    
    // MARK: - UIKit elements -
    
    @IBOutlet weak var firstNameTextField: UITextField!
    @IBOutlet weak var lastNameTextField: UITextField!
    @IBOutlet weak var countryTextField: UITextField!
    @IBOutlet weak var phoneCodeLabel: UILabel!
    @IBOutlet weak var phoneTextField: UITextField!
    var countryPickerView = UIPickerView()
    
    // MARK: - Public properties -

    var presenter: SendMoneyPresenterInterface!
    var countries: [Country] = [
        Country(name: "Kenya", code: "KES", phonePrefix: "+254", digitsAfterPrefix: 9),
        Country(name: "Nigeria", code: "NGN", phonePrefix: "+234", digitsAfterPrefix: 7),
        Country(name: "Tanzania", code: "TZS", phonePrefix: "+255", digitsAfterPrefix: 9),
        Country(name: "Uganda", code: "UGX", phonePrefix: "+256", digitsAfterPrefix: 7)
    ]
    var selectedCountry: Country?

    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupCountryTextField()
    }
    
    fileprivate func setupCountryTextField() {
        countryTextField.inputView = countryPickerView
        countryPickerView.delegate = self
        countryPickerView.dataSource = self
    }

}

// MARK: - Extensions -

extension SendMoneyViewController: SendMoneyViewInterface {
}

extension SendMoneyViewController: UIPickerViewDelegate {
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        countryTextField.text = countries[row].name
        phoneCodeLabel.text = countries[row].phonePrefix
        countryTextField.resignFirstResponder()
    }
}

extension SendMoneyViewController: UIPickerViewDataSource {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return countries.count
    }
    
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        return "\(countries[row].phonePrefix) - \(countries[row].name)"
    }
}
