//
//  SendMoneyWireframe.swift
//  Penguin Pay
//
//  Created by John Edwin Guerrero Ayala on 16/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SendMoneyWireframe: BaseWireframe<SendMoneyViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "SendMoney", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: SendMoneyViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = SendMoneyFormatter()
        let interactor = SendMoneyInteractor()
        let presenter = SendMoneyPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SendMoneyWireframe: SendMoneyWireframeInterface {
}
