//
//  SendMoneyFormatter.swift
//  Penguin Pay
//
//  Created by John Edwin Guerrero Ayala on 16/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SendMoneyFormatter {
}

// MARK: - Extensions -

extension SendMoneyFormatter: SendMoneyFormatterInterface {
}
