//
//  SendMoneyPresenter.swift
//  Penguin Pay
//
//  Created by John Edwin Guerrero Ayala on 16/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SendMoneyPresenter {

    // MARK: - Private properties -

    private unowned let view: SendMoneyViewInterface
    private let formatter: SendMoneyFormatterInterface
    private let interactor: SendMoneyInteractorInterface
    private let wireframe: SendMoneyWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: SendMoneyViewInterface,
        formatter: SendMoneyFormatterInterface,
        interactor: SendMoneyInteractorInterface,
        wireframe: SendMoneyWireframeInterface
    ) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension SendMoneyPresenter: SendMoneyPresenterInterface {
}
